myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

# from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", home),
    path("about/", about),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from .views import *

app_name = "posts"

urlpatterns = [
    path("", posts_lists, name="list"),
    path("new-post", post_new, name="new-post"),
    path("<slug:slug>", post_page, name="page"),
]

myproject/user/urls.py
from django.urls import path
from .views import *

app_name = "user"

urlpatterns = [
    path("register/", register, name="register"),
]

myproject/users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path("register/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path("send-email/", send_email_view, name="send-email"),
    path(
        "send-email-with-template/",
        send_email_with_template_view,
        name="send-email-with-template",
    ),
    path("logout/", logout_view, name="logout"),
]

myproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default="fallback.png", blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

myproject/users/models.py
from django.db import models

# Create your models here.


class SendEmail(models.Model):
    subject = models.CharField(max_length=50)
    message = models.TextField()
    from_email = models.EmailField(max_length=254)
    to_email = models.EmailField(max_length=254)
    status = models.BooleanField()
    attachment = models.FileField(upload_to=None, max_length=100, blank=True)

    def __str__(self):
        return f"{self.to_email} | {self.subject}"

myproject/posts/forms.py
from django import forms
from . import models


class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ["title", "body", "slug", "banner"]

myproject/users/forms.py
from django import forms
from .models import *

# Form With Model
# class SendEmailForm(forms.ModelForm):

#     class Meta:
#         model = SendEmail
#         fields = ["subject", "message", "to_email", "attachment"]


class SendEmailForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    to_email = forms.EmailField(label="To")
    attachment = forms.FileField(required=False)


class SendEmailWithTemplateForm(forms.Form):
    choices = (
        ("users/email_template_4th_of_July.html", "4th Of July"),
        ("users/email_template_father's_day.html", "Father's Day"),
        ("users/email_template_hotel_offer.html", "Hotel Offer"),
    )
    subject = forms.CharField(max_length=100, required=True)
    message = forms.CharField(
        widget=forms.Textarea, label="Message (fallback message):", required=False
    )
    username = forms.CharField(max_length=100, required=True)
    to_email = forms.EmailField(label="To", required=True)
    template = forms.ChoiceField(choices=choices, required=False)
    attachment = forms.FileField(required=False)

myproject/myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    # return HttpResponse("Hello World.")
    return render(request, "home.html")


def about(request):
    # return HttpResponse("About Page")
    return render(request, "about.html")

myproject/posts/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.


def posts_lists(request):
    posts = Post.objects.all().order_by("-date")
    return render(request, "posts/posts_lists.html", {"posts": posts})


def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, "posts/post_page.html", {"post": post})


@login_required(login_url="/users/login/")
def post_new(request):
    if request.method == "POST":
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect("posts:list")
    else:
        form = forms.CreatePost()
    return render(request, "posts/post_new.html", {"form": form})

myproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from . import forms
from .utils import send_mails, SendEmailMessage, SendEmailWithTemplate


# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", {"form": form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")


def send_email_view(request):
    if request.method == "POST":
        form = forms.SendEmailForm(request.POST, request.FILES)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            message = form.cleaned_data["message"]
            to_email = form.cleaned_data["to_email"]
            attachment = request.FILES.get("attachment")

            SendEmailMessage(subject, message, to_email, attachment)

            form = forms.SendEmailForm()
    else:
        form = forms.SendEmailForm()
    return render(request, "users/send_email.html", {"form": form})


def send_email_with_template_view(request):
    if request.method == "POST":
        form = forms.SendEmailWithTemplateForm(request.POST, request.FILES)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            message = form.cleaned_data["message"]
            username = form.cleaned_data["username"]
            to_email = form.cleaned_data["to_email"]
            template = form.cleaned_data["template"]
            attachment = request.FILES.get("attachment")

            SendEmailWithTemplate(
                subject, message, username, to_email, template, attachment
            )

            form = forms.SendEmailWithTemplateForm()

    else:
        form = forms.SendEmailWithTemplateForm()
    return render(request, "users/send_email_with_template.html", {"form": form})

myproject/posts/templates/posts/post_new.html
{% extends "layout.html" %}

{% block title %}
   New Post
{% endblock title %}

{% block content %}
    <section>
        <h1>New Post</h1>
        <form class="form-with-validation" action={% url "posts:new-post" %} method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit" >Submit</button>
        </form>
    </section>
{% endblock content %}

myproject/posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
   {{ post.title }}
{% endblock title %}

{% block content %}
<section>
   <img src={{ post.banner.url }} alt={{ post.title }} class="banner" >
   <h1>{{ post.title }}</h1>
   <p>{{ post.date }} by {{ post.author }} </p>
   <p>{{ post.body }}</p>
</section>
{% endblock content %}

myproject/posts/templates/posts/posts_lists.html
{% extends "layout.html" %}

{% block title %}
   Post
{% endblock title %}

{% block content %}
<section>
   <h1>Post</h1>
   {% for post in posts %}
      <article class='post'>
         <a href={% url "posts:page" slug=post.slug %}>
            <h2>{{ post.title }}</h2>
         </a>
         <p>{{ post.date }} by {{ post.author }}</p>
         <p>{{ post.body }}</p>
      </article>
   {% endfor %}
</section>
{% endblock content %}

myproject/templates/about.html
{% extends "layout.html" %}

{% block title %}
   About
{% endblock title %}

{% block content %}
   <h1>About</h1>
   <p>Go to <a href="/">Home</a> Page.</p>
{% endblock content %}

myproject/templates/home.html
{% extends "layout.html" %}

{% block title %}
   Home
{% endblock title %}

{% block content %}
   <h1>Home</h1>
   <p>Go to <a href="/about">About</a> Page.</p>
{% endblock content %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href={% static "css/style.css" %}>
   <script src={% static "js/script.js" %} defer ></script>
   <title>
      {% block title %}
         Django App
      {% endblock title %}
   </title>
</head>
<body>
   <nav>
      <a href="/">
         <span role="img" aria-label="Home" title="Home" >🏠</span>
      </a> | 
      <a href="/about">
         <span role="img" aria-label="About" title="About" >😀</span>
      </a> | 
      <a href={% url "posts:list" %}>
         <span role="img" aria-label="Posts" title="Posts" >📰</span>
      </a> |
      {% if user.is_authenticated %}
         <a href="{% url 'posts:new-post' %}">
            <span role="img" aria-label="New Post" title="New Post">🆕</span>
         </a> |
         <a href="{% url 'users:send-email' %}">
            <span role="img" aria-label="Send Email" title="Send Email">✉️</span>
         </a> |
         <a href="{% url 'users:send-email-with-template' %}">
            <span role="img" aria-label="Send Email With Template" title="Send Email With Template">📋</span>
         </a> |
         <form class="logout" action={% url "users:logout" %} method="post">
            {% csrf_token %}
            <button class="logout-button" aria-label="User Logout" title="User Logout" >👋</button>
         </form>
      {% else %}
         <a href={% url 'users:register' %}>
            <span role="img" aria-label="User Registration" title="User Registration">🚀</span>
         </a> |
         <a href="{% url 'users:login' %}">
            <span role="img" aria-label="User Login" title="User Login">🔏</span>
         </a>
      {% endif %}
  </nav>
  <main>
   {% block content %}
   {% endblock content %}
  </main>
</body>
</html>

myproject/users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
   User Login
{% endblock title %}

{% block content %}
   <h1>User Login</h1>
   <form class="form-with-validation" action={% url "users:login" %} method="post">
      {% csrf_token %}
      {{ form }}
      {% if request.GET.next %}
         <input type="hidden" name="next" value={{ request.GET.next }} />
      {% endif %}
      <button class="form-submit" >Submit</button>
   </form>
{% endblock content %}

myproject/users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
   Register User
{% endblock title %}

{% block content %}
   <h1>Register A New User</h1>
   <form class="form-with-validation" action={% url "users:register" %} method="post">
      {% csrf_token %}
      {{ form }}
      <button class="form-submit" >Submit</button>
   </form>
{% endblock content %}

myproject/users/templates/users/send_email.html
{% extends "layout.html" %}

{% block title %}
   Send Email
{% endblock title %}

{% block content %}
   <h1>Send Email</h1>
   <form class="form-with-validation" action={% url "users:send-email" %} method="post">
      {% csrf_token %}
      {{ form }}
      <button class="form-submit" >Send</button>
   </form>
{% endblock content %}

myproject/users/templates/users/send_email_with_template.html
{% extends "layout.html" %}

{% block title %}
   Send Email With Template
{% endblock title %}

{% block content %}
   <h1>Send Email With Template</h1>
   <form class="form-with-validation" action={% url "users:send-email-with-template" %} method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <button class="form-submit" >Send</button>
   </form>
{% endblock content %}